workspace = { members = ["src/newwin-framework", "src/newwin-framework/PMF"] }
[package]
name = "newwin"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
